
---

- name: Create file1
  copy:
    dest: /home/usr1/file1.txt
    content: |
      Text Line1, in file1
      Text Line2, in file1
      Text Line2, {{ mytext }}

- name: Create file2
  copy:
    dest: /home/usr1/file2.txt
    content: |
      Text Line1, in file2
      Text Line2, in file2
      Text Line2, {{ mytext }}
