
---
- name: Install Apache and Upload my Web Page
  hosts: CENTOS
  become: yes

  vars:
    WP_HOSTNAME: wordpress1.com
    WP_APP_NAME: wordpress1
    WP_USER_NAME: usr1
    WP_PASSWORD: 12345

  tasks:
    - name: Ping test
      ping:
  
    - name: Apt update and upgrade
      shell: |
        sudo yum update
        sudo yum upgrade -y
        
    - name: Install all packages to WP
      shell:
        "yum install httpd \
                     ghostscript \
                     libapache2-mod-php \
                     mysql-server \
                     php \
                     php-bcmath \
                     php-curl \
                     php-imagick \
                     php-intl \
                     php-json \
                     php-mbstring \
                     php-mysql \
                     php-xml \
                     php-zip -y"

    - name: Create and load wordpress
      shell: 
        mkdir -p /srv/www/"{{ WP_APP_NAME }}"
    - name: Change owner to usr1
      shell:  
        chown -R "{{ WP_USER_NAME }}"":""{{ WP_USER_NAME }}" /srv/www/"{{ WP_APP_NAME }}"
    - name: Install and load WP 
      shell: 
        curl https://wordpress.org/latest.tar.gz | sudo -u "{{ WP_USER_NAME }}" tar zx -C /srv/www/"{{ WP_APP_NAME }}"           

    - name: create sites-avaible
      shell: |
        mkdir /etc/httpd/sites-available
        mkdir /etc/httpd/sites-enabled
        
    
    - name: Create "{{ WP_APP_NAME }}".conf apache2
      shell: |
        echo '<VirtualHost *:80>
            ServerName {{ WP_HOSTNAME }}
            DocumentRoot /srv/www/{{ WP_APP_NAME }}/wordpress
            <Directory /srv/www/{{ WP_APP_NAME }}/wordpress>
                Options FollowSymLinks
                AllowOverride Limit Options FileInfo
                DirectoryIndex index.php
                Require all granted
            </Directory>
            <Directory /srv/www/{{ WP_APP_NAME }}/wordpress/wp-content>
                Options FollowSymLinks
                Require all granted
            </Directory>
        </VirtualHost>' > /etc/apache2/sites-available/"{{ WP_APP_NAME }}".conf

    - name: Setting up Apache2
      shell: |
        a2ensite "{{ WP_APP_NAME }}"
        a2enmod rewrite
        a2dissite 000-default
        service apache2 reload 
    
  
    - name: Setting up mySQL 
      shell:
        sudo mysql -u root -e "CREATE DATABASE {{ WP_APP_NAME }}";
        sudo mysql -u root -e "CREATE USER '{{ WP_USER_NAME }}'@'%' IDENTIFIED BY '{{ WP_PASSWORD }}'";
        sudo mysql -u root -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER ON "{{ WP_APP_NAME }}".* TO '{{ WP_USER_NAME }}'@'%'";
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
    
    - name: Setting up mySQL 
      shell:
        sudo service mysql start

    - name: copy wp-config.php 
      shell:
        cp /srv/www/"{{ WP_APP_NAME }}"/wordpress/wp-config-sample.php /srv/www/"{{ WP_APP_NAME }}"/wordpress/wp-config.php 

    - name: Change line wp-config1
      shell: |     
        sed -i "s/'database_name_here'/'"{{ WP_APP_NAME }}"'/g" /srv/www/"{{ WP_APP_NAME }}"/wordpress/wp-config.php
        sed -i "s/'username_here'/'"{{ WP_USER_NAME }}"'/g" /srv/www/"{{ WP_APP_NAME }}"/wordpress/wp-config.php
        sed -i "s/'password_here'/'"{{ WP_PASSWORD }}"'/g" /srv/www/"{{ WP_APP_NAME }}"/wordpress/wp-config.php
   #если на другом сервере sed -i "s/'localhost'/'"{{ WP_HOSTNAME }}"'/g" /srv/www/"{{ WP_APP_NAME }}"/wordpress/wp-config.php
        
    - name: Change line wp-config2
      shell: |
        SALT=$(curl -L https://api.wordpress.org/secret-key/1.1/salt/)
        STRING='put your unique phrase here'
        printf '%s\n' "g/$STRING/d" a "$SALT" . w | ed -s /srv/www/"{{ WP_APP_NAME }}"/wordpress/wp-config.php
      
  #это пишу, если mysql на другом сервере   - name: Change mysql config
  #это пишу, если mysql на другом сервере     shell: |
  #это пишу, если mysql на другом сервере       config_file="/etc/mysql/mysql.conf.d/mysqld.cnf"
  #это пишу, если mysql на другом сервере       old_host="127.0.0.1"
  #это пишу, если mysql на другом сервере       new_host="0.0.0.0"
  #это пишу, если mysql на другом сервере       sudo sed -i "s/$old_host/$new_host/g" "$config_file"

  #  - name: restart mysql
  #    shell: |
  #      sudo service mysql restart 


  

