stages:
  - start-job
  - download_repository
  - build
  - push
  - test
  - deploy

variables:
  REPO_NAME: "sergeypetkov"
  REMOTE_APP_DIR: "simple-django-project"
  REMOTE_HOST: "usr1@192.168.1.194" 

start-job:
  stage: start-job
  script:
    - echo "DOCKER_IMAGE_TAG=1.0.$CI_PIPELINE_ID-$(date +%Y%m%d%H%M)" >> start-job.env
  artifacts:
    reports:
      dotenv: start-job.env

download_repository:    
  stage: download_repository
  script:
    - cd $HOME
    - rm -rf $REMOTE_APP_DIR
    - git clone git@master.gitlab:root/$REMOTE_APP_DIR.git
    - cd ~/$REMOTE_APP_DIR
    - git checkout origin/deploy
    - sed -e "s/my-new-version/'$DOCKER_IMAGE_TAG'/g" ~/$REMOTE_APP_DIR/templates/signup.html.tpl > ~/$REMOTE_APP_DIR/templates/signup.html
  dependencies:
    - start-job

build-job:       
  stage: build
  script:
    - cd $HOME/$REMOTE_APP_DIR
    - docker build -t $REPO_NAME/gitlabrepo:$DOCKER_IMAGE_TAG -f $HOME/$REMOTE_APP_DIR/Dockerfile .
    - echo "Build complete."
  dependencies:
    - start-job

push-job:
  stage: push
  script:
    - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
    - docker push "$REPO_NAME"/gitlabrepo:"$DOCKER_IMAGE_TAG"
  dependencies:
    - start-job
  
unit-test-job:  
  stage: test   
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"

lint-test-job:   
  stage: test
  script:
    - echo "Linting code... This will take about 5 seconds."
    - echo "No lint issues found."

deploy-job:      
  stage: deploy  
  environment: production
  script:
    - scp -o StrictHostKeyChecking=accept-new ~/$REMOTE_APP_DIR/compose.yaml $REMOTE_HOST:~/$REMOTE_APP_DIR
    - ssh $REMOTE_HOST "whoami"
    - ssh $REMOTE_HOST "TAG=\"$DOCKER_IMAGE_TAG\" docker compose -f ~/$REMOTE_APP_DIR/compose.yaml up -d --build --force-recreate"
  dependencies:
    - start-job
